
default_language_version:
    python: python3
exclude: (^docs/(conf.py|_ext/)|^plate_simulation-assets/)
default_stages: [commit,push]
fail_fast: false

ci:
    skip: [pylint]
    autoupdate_branch: develop
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    -   id: ruff
        args:
        -   --fix
        -   --exit-non-zero-on-fix
#        -   --unsafe-fixes
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        additional_dependencies: [
            numpy==1.23.*,
            types-toml,
            types-PyYAML,
            tomli # to read config from pyproject.toml
        ]
-   repo: https://github.com/codingjoe/relint
    rev: 3.1.0
    hooks:
    -   id: relint
        args: [-W]  # to fail on warnings
-   repo: https://github.com/MiraGeoscience/pre-commit-hooks
    rev: v1.0.1
    hooks:
    -   id: check-copyright
        files: (^LICENSE|^README(|-dev).rst|\.py|\.pyi)$
        exclude: (^\.|^docs/)
    -   id: prepare-commit-msg
    -   id: check-commit-msg
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: .\\devtools\\conda_env_pylint.bat
        language: system
        require_serial: true  # pylint does its own parallelism
        types: [python]
        exclude: ^(devtools|docs)/
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        exclude: (-lock\.ya?ml|\benvironments/.*\.ya?ml|\.ipynb|^THIRD_PARTY_SOFTWARE\.rst)$
        entry: codespell -I .codespellignore
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.mdj$
    -   id: check-toml
    -   id: check-yaml
#    -   id: check-added-large-files # crashing on some configuration. To be investigated
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        exclude: \.mdj$
    -   id: mixed-line-ending
    -   id: name-tests-test
-   repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.0
    hooks:
    -   id: rstcheck
        exclude: ^THIRD_PARTY_SOFTWARE.rst$
        additional_dependencies: [sphinx]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
        exclude: ^THIRD_PARTY_SOFTWARE.rst$
