[tool.poetry]
name = "plate-simulation"
version = "0.1.0-beta.1"
license = "MIT"
description = "plate-simulation is a Python package"
authors = ["Mira Geoscience <support@mirageoscience.com>"]
readme = "README.rst"
repository = "https://github.com/MiraGeoscience/plate-simulation"
documentation  = "https://mirageoscience-plate-simulation.readthedocs-hosted.com/"
homepage = "https://mirageoscience.com"
keywords = []

# TODO: adjust classifiers
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Natural Language :: English",
]

packages = [
    { include = "plate_simulation" },
    { include = "plate_simulation-assets" },
]

include = [
    { path = "COPYING", format = ["sdist", "wheel"] },
    { path = "COPYING.LESSER", format = ["sdist", "wheel"] },
    { path = "LICENSE", format = ["sdist", "wheel"] },
    { path = "README.rst", format = ["sdist", "wheel"] },
    { path = "THIRD_PARTY_SOFTWARE.rst", format = ["sdist", "wheel"] },
    { path = "docs/**/THIRD_PARTY_SOFTWARE.rst", format = ["sdist", "wheel"] },
]

exclude = [
]

[tool.poetry.dependencies]
python = "^3.10, <3.11"

numpy = "~1.26.0"  # also in geoh5py, simpeg and geoana
scipy = "~1.14.0"  # also in geoapps-utils
discretize = "~0.10.0"  # also in simpeg, simpeg-drivers, octree-creation-app
Rtree = "~1.2.0"
trimesh = "~4.1.3"
threadpoolctl = "~3.3.0"
pydantic = "~2.5.2"

## Pip dependencies from Git repositories
#----------------------------------------
#geoh5py = {version = "~0.10.0-alpha.1", source = "pypi", allow-prereleases = true}
geoh5py = {git = "https://github.com/MiraGeoscience/geoh5py.git", rev = "develop"}

#param-sweeps = {version = "~0.1.8-alpha.1", source = "pypi", allow-prereleases = true}
param-sweeps = {git = "https://github.com/MiraGeoscience/param-sweeps.git", rev = "develop"}

#geoapps-utils = {version = "~0.4.0-alpha.1", source = "pypi", allow-prereleases = true}
geoapps-utils = {git = "https://github.com/MiraGeoscience/geoapps-utils.git", rev = "develop"}

#octree-creation-app = {version = "~0.2.0-alpha.1", source = "pypi", allow-prereleases = true}
octree-creation-app = {git = "https://github.com/MiraGeoscience/octree-creation-app.git", rev = "develop"}

#mira-simpeg = {version = ">=0.21.2.1-alpha.1, <0.21.2.2.dev", source = "pypi", allow-prereleases = true}
mira-simpeg = {git = "https://github.com/MiraGeoscience/simpeg.git", rev = "develop"}

#simpeg-drivers = {version = "~0.2.0-alpha.1", source = "pypi", allow-prereleases = true}
simpeg-drivers = {git = "https://github.com/MiraGeoscience/simpeg-drivers.git", rev = "develop" }

## about pip dependencies
# to be specified to work with conda-lock
# - from PyPI: my_package = { version = "1.2.3", source = "pypi" }
# - from URL:
#   - for a tags:   my_package = { url = "https://github.com/ORGANISATION/REPO/archive/refs/tags/VERSION_TAG.zip#sha256=" }
#   - for a branch: my_package = { url = "https://github.com/ORGANISATION/REPO/archive/refs/heads/BRANCH.zip#sha256=" }
# Note - conda-lock does not support the syntax: my_package = { git = ... }
#        while poetry2conda supports only { git = "...", tag = "..." }, and not { url = ... }


[tool.conda-lock.dependencies]
libblas = "*=*mkl"  # because simpeg already brings in the MKL

## indirect dependencies, forcing them here for installation through Conda not pip
#---------------------------------------------------------------------------------
Pillow = ">=10.3.0, <10.4.0"  # from geoh5py
dask = {version = "2024.6.*", extras = ["distributed"]}
distributed = "2024.6.*"  # because conda-lock doesn't take dask extras into account
empymod = ">=2.2.1, <2.3.0"  # from simpeg and geoana
fsspec = "2022.*"  # from simpeg[dask]
geoana = ">=0.5.0, <0.6.0"  # from simpeg
h5py = ">=3.2.1, <4.0.0"  # from geoh5py
matplotlib-base = ">=3.8.4, <3.9.0"  # from simpeg
mkl = "2023.2, <2023.3"  # from simpeg
pandas = ">=2.2.1, <2.3.0"  # from simpeg
pydiso = ">=0.0.5, <0.1.0"  # from simpeg
pymatsolver = ">=0.2.0, <0.3.0"  # from simpeg
scikit-learn = ">=1.4.0, <1.5.0"  # from simpeg
tqdm = ">=4.66.1, <5.0.0"  # from curve-apps, peak-finder-app, simpeg
zarr = ">=2.14.2, <2.15.0"  # from simpeg[dask], simpeg-drivers

# force some versions to resolve incompatible resolution between PyPI and Conda
#-------------------------------------------------------------------------------
tbb = "2021.12.*"  # through mkl from SimPEG (constraint copied from simpeg-drivers)
python-tzdata = "2023.4.*"  # through pandas from SimPEG (constraint copied from simpeg-drivers)

[tool.poetry.dev-dependencies]
Pygments = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
tomli = "*"
sphinx = "^5.0"
readthedocs-sphinx-ext = "*"

[tool.conda-lock]
platforms = ["win-64", "linux-64"]
channels = ["conda-forge"]

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
ignore = [
    "B028",  # no-explicit-stacklevel for warnings.warn()
    "E501",  # line-too-long - code is reformatted (do not care about comments and docstring)
    "F401",  # unsused-import - covered by pycln
]
select = [
    "A",  # flake8-builtins
    "B",  # flake8-bugbear
    "B006",  # Do not use mutable data structures for argument defaults
    "B9",  # flake8-bugbear opiniated warnings
    "BLE",  # flake8-blind-except
    "C4",  # flake8-comprehensions
    "C9",  # mccabe
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "RUF",  # ruff rules
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade
    "W",  # pycodestyle warnings
]

[tool.ruff.lint.mccabe]
max-complexity = 18

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.format]
# default formatting is just fine

[tool.mypy]
warn_unused_configs = true
ignore_missing_imports = true
scripts_are_modules = true
show_error_context = true
show_column_numbers = true
check_untyped_defs = true

plugins = [
    'numpy.typing.mypy_plugin'
]

[tool.coverage.run]
branch = true
source = ["plate_simulation"]

[tool.coverage.report]
exclude_lines = [
    "raise NotImplementedError",
    "pass",
    "if TYPE_CHECKING",
    "pragma: no cover"
]

[tool.coverage.html]
skip_empty = true
skip_covered = true

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools"]
build-backend = "poetry.core.masonry.api"
