schema_version: 1

context:
  name: "plate-simulation"
  version: "0.1.1a1"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoh5py >=0.10.1, <0.11.dev
    - param-sweeps >=0.2.0, <0.3.dev
    - geoapps-utils >=0.4.0, <0.5.dev
    - octree-creation-app >=0.2.0. <0.3.dev
    - mira-simpeg >=0.21.2.2a1, <0.21.3.dev
    - simpeg-drivers >=0.2.1a2, <0.3.dev
    # direct dependencies
    - numpy >=1.26.0, <1.27.dev
    - rtree >=1.2.0, <1.3.dev
    - scipy >=1.14.0, <1.15.dev
    - trimesh >=4.1.3, <4.2.dev
    - threadpoolctl >=3.3.0, <3.4.dev
    - pydantic >=2.5.2, <2.6.dev
  run_constraints:
    - __glibc >=2.17

about:
  summary: |
    Specialized mesh, model and simulation for a parameterization of
    the halfspace + overburden and plate geological setting
  license: MIT
  license_file: LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/geoscience-analyst/python-integration/
  repository: https://github.com/MiraGeoscience/plate-simulation
  documentation: https://mirageoscience-plate-simulation.readthedocs-hosted.com/en/release-0.1.0/

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
