schema_version: 1

context:
  name: "plate-simulation"
  version: "0.2.0a1"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../${{ name }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.26.0,<1.27.0
    - scipy >=1.14.0,<1.15.0
    - rtree >=1.2.0,<1.3.0
    - trimesh >=4.1.3,<4.2.0
    - threadpoolctl >=3.3.0,<3.4.0
    - pydantic >=2.5.2,<2.6.0
    - geoh5py 0.10.*
    - param-sweeps 0.2.*
    - geoapps-utils 0.4.*
    - octree-creation-app 0.2.*
    - mira-simpeg >=0.21.2.1,<0.22.2.2a.dev
    - simpeg-drivers 0.2.*
    - pillow >=10.3.0,<10.4.0
    - dask 2024.6.*
    - discretize >=0.10.0,<0.11.0
    - distributed 2024.6.*
    - empymod >=2.2.1,<2.3.0
    - fsspec 2022.*
    - geoana >=0.5.0,<0.6.0
    - h5py >=3.2.1,<4.0.0
    - matplotlib-base >=3.8.4,<3.9.0
    - mkl >=2023.2,<2023.3
    - pandas >=2.2.1,<2.3.0
    - pydiso >=0.1.0, <0.2.0
    - pymatsolver >=0.2.0,<0.3.0
    - scikit-learn >=1.4.0,<1.5.0
    - tqdm >=4.66.1,<5.0.0
    - zarr >=2.14.2,<2.15.0
    - tbb 2021.12.*
    - python-tzdata 2023.4.*
  run_constraints:
    - __glibc >=2.17

about:
  summary: |
    Specialized mesh, model and simulation for a parameterization of
    the halfspace + overburden and plate geological setting
  license: MIT
  license_file: LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/geoscience-analyst/python-integration/
  repository: https://github.com/MiraGeoscience/plate-simulation
  documentation: https://mirageoscience-plate-simulation.readthedocs-hosted.com/en/release-0.1.0/

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
